version: '3.3'
services:
  db:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: '123456'
  channels_db:
    image: redis
  web:
    build: .
    depends_on:
      - db
      - channels_db
    command: ['./wait-for-it.sh', 'db:3306', '--', './setup-start.sh']
    restart: always
    ports:
      - "80:8000"

networks:
  db:
  channels_db:
  web:

